apiVersion: v1

kind: Service

metadata:
  name: k8s-test-app-service
  
spec:
  selector:
    app: k8s-test-app
  ports:
    - protocol: TCP
      port: 30566
      targetPort: 80
      nodePort: 30080
  type: NodePort
