apiVersion: v1

kind: Service

metadata:
  name: k8s-test-app-service
  
spec:
  selector:
    app: k8s-test-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      # nodePort: 30000
  type: NodePort
